import { z } from 'zod';

/**
 * Activity Feed Schemas - Validation schemas for team activity events
 *
 * Live feed of team events within the active workspace.
 * Events are generated by database triggers and streamed via Supabase Realtime.
 */

// =============================================================================
// ENUMS
// =============================================================================

/**
 * Activity event type enum - matches database activity_event_type ENUM
 *
 * Events tracked:
 * - timer_started: User started a timer on a project
 * - timer_stopped: User stopped a timer (includes duration)
 * - entry_logged: User logged a time entry
 * - goal_created: User created a goal
 * - goal_completed: User completed a goal
 * - entry_approved: Approver approved entries
 * - entry_rejected: Approver rejected entries
 * - member_joined: User joined the workspace
 * - member_left: User left the workspace
 * - member_role_changed: User's role was changed
 * - project_created: New project was created
 * - project_member_added: User was added to a project
 */
export const ActivityEventTypeEnum = z.enum([
  'timer_started',
  'timer_stopped',
  'entry_logged',
  'goal_created',
  'goal_completed',
  'entry_approved',
  'entry_rejected',
  'member_joined',
  'member_left',
  'member_role_changed',
  'project_created',
  'project_member_added',
]);

/**
 * All activity event types as a readonly array
 */
export const ALL_ACTIVITY_EVENT_TYPES = ActivityEventTypeEnum.options;

// =============================================================================
// PAYLOAD SCHEMAS
// =============================================================================

/**
 * Base activity payload - flexible JSONB structure
 * Different event types have different payload shapes.
 */
export const ActivityEventPayloadSchema = z.record(z.string(), z.unknown());

/**
 * Timer started payload
 */
export const TimerStartedPayloadSchema = z.object({
  project_id: z.string().uuid().optional(),
  project_name: z.string().optional(),
  category_id: z.string().uuid().optional(),
  category_name: z.string().optional(),
});

/**
 * Timer stopped payload
 */
export const TimerStoppedPayloadSchema = z.object({
  project_id: z.string().uuid().optional(),
  project_name: z.string().optional(),
  duration_seconds: z.number().int().nonnegative(),
});

/**
 * Entry logged payload
 */
export const EntryLoggedPayloadSchema = z.object({
  entry_id: z.string().uuid(),
  project_id: z.string().uuid().optional(),
  project_name: z.string().optional(),
  category_id: z.string().uuid().optional(),
  category_name: z.string().optional(),
  duration_seconds: z.number().int().nonnegative(),
});

/**
 * Entry approval payload (approved/rejected)
 */
export const EntryApprovalPayloadSchema = z.object({
  member_user_id: z.string().uuid(),
  member_name: z.string().nullable(),
  entry_count: z.number().int().positive(),
  date_range_start: z.string().datetime({ offset: true }).optional(),
  date_range_end: z.string().datetime({ offset: true }).optional(),
  rejection_reason: z.string().optional(),
});

/**
 * Goal payload (created/completed)
 */
export const GoalPayloadSchema = z.object({
  goal_id: z.string().uuid(),
  goal_type: z.enum(['overall', 'category', 'type']),
  target_hours: z.number().nonnegative(),
  category_id: z.string().uuid().optional(),
  category_name: z.string().optional(),
});

/**
 * Member payload (joined/left/role changed)
 */
export const MemberPayloadSchema = z.object({
  user_id: z.string().uuid(),
  user_name: z.string().nullable(),
  user_email: z.string().email(),
  old_role: z.enum(['owner', 'admin', 'member']).optional(),
  new_role: z.enum(['owner', 'admin', 'member']).optional(),
});

/**
 * Project payload (created)
 */
export const ProjectCreatedPayloadSchema = z.object({
  project_id: z.string().uuid(),
  project_name: z.string(),
  project_color: z.string(),
});

/**
 * Project member added payload
 */
export const ProjectMemberAddedPayloadSchema = z.object({
  project_id: z.string().uuid(),
  project_name: z.string(),
  added_user_id: z.string().uuid(),
  added_user_name: z.string().nullable(),
  role: z.enum(['owner', 'admin', 'member']),
});

// =============================================================================
// ENTITY SCHEMAS
// =============================================================================

/**
 * Activity Event Schema - Entity schema for query responses
 *
 * Represents a single activity event in the workspace feed.
 */
export const ActivityEventSchema = z.object({
  /** UUID primary key */
  id: z.string().uuid(),

  /** UUID of the workspace this event belongs to */
  workspace_id: z.string().uuid(),

  /** UUID of the user who performed the action */
  actor_user_id: z.string().uuid(),

  /** Type of event */
  event_type: ActivityEventTypeEnum,

  /**
   * Event-specific payload data
   * Structure varies by event_type
   */
  payload: ActivityEventPayloadSchema.default({}),

  /** Timestamp when event occurred */
  created_at: z.string().datetime({ offset: true }),
});

/**
 * Activity Event With Actor Schema - Includes actor user details
 *
 * Used for displaying events in the feed with user information.
 */
export const ActivityEventWithActorSchema = ActivityEventSchema.extend({
  /** Actor user details */
  actor: z.object({
    id: z.string().uuid(),
    email: z.string().email(),
    name: z.string().nullable(),
  }),
});

/**
 * Activity Feed Page Schema - Paginated activity feed response
 */
export const ActivityFeedPageSchema = z.object({
  /** List of events on this page */
  events: z.array(ActivityEventWithActorSchema),

  /** Cursor for fetching the next page */
  next_cursor: z.string().nullable(),

  /** Whether there are more events to fetch */
  has_more: z.boolean(),
});

// =============================================================================
// FILTER SCHEMAS
// =============================================================================

/**
 * Activity Feed Filter Schema - For filtering events
 */
export const ActivityFeedFilterSchema = z.object({
  /** Filter by workspace ID (defaults to active workspace) */
  workspaceId: z.string().uuid().optional(),

  /** Filter by event types */
  eventTypes: z.array(ActivityEventTypeEnum).optional(),

  /** Filter by actor user ID */
  actorId: z.string().uuid().optional(),

  /** Only show events after this timestamp */
  since: z.string().datetime({ offset: true }).optional(),

  /** Only show events before this timestamp */
  until: z.string().datetime({ offset: true }).optional(),

  /** Maximum number of events to return */
  limit: z.number().int().positive().max(100).default(20),

  /** Cursor for pagination */
  cursor: z.string().optional(),
});

// =============================================================================
// REALTIME SCHEMAS
// =============================================================================

/**
 * Activity Event Realtime Payload Schema
 *
 * Shape of the payload received from Supabase Realtime subscriptions.
 */
export const ActivityEventRealtimePayloadSchema = z.object({
  /** Event type from Supabase */
  eventType: z.literal('INSERT'),

  /** The newly created activity event */
  new: ActivityEventSchema,

  /** Schema name */
  schema: z.literal('public'),

  /** Table name */
  table: z.literal('activity_feed'),
});

// =============================================================================
// HELPER CONSTANTS
// =============================================================================

/**
 * Human-readable event type names for display
 */
export const EVENT_TYPE_NAMES: Record<z.infer<typeof ActivityEventTypeEnum>, string> = {
  timer_started: 'Timer Started',
  timer_stopped: 'Timer Stopped',
  entry_logged: 'Time Logged',
  goal_created: 'Goal Created',
  goal_completed: 'Goal Completed',
  entry_approved: 'Entry Approved',
  entry_rejected: 'Entry Rejected',
  member_joined: 'Member Joined',
  member_left: 'Member Left',
  member_role_changed: 'Role Changed',
  project_created: 'Project Created',
  project_member_added: 'Added to Project',
};

/**
 * Event type categories for grouping/filtering
 */
export const EVENT_TYPE_CATEGORIES = {
  timer: ['timer_started', 'timer_stopped'] as const,
  entries: ['entry_logged', 'entry_approved', 'entry_rejected'] as const,
  goals: ['goal_created', 'goal_completed'] as const,
  members: ['member_joined', 'member_left', 'member_role_changed'] as const,
  projects: ['project_created', 'project_member_added'] as const,
} as const;

// =============================================================================
// INFERRED TYPES
// =============================================================================

/** Activity event type */
export type ActivityEventType = z.infer<typeof ActivityEventTypeEnum>;

/** Activity event payload (generic) */
export type ActivityEventPayload = z.infer<typeof ActivityEventPayloadSchema>;

/** Activity event */
export type ActivityEvent = z.infer<typeof ActivityEventSchema>;

/** Activity event with actor details */
export type ActivityEventWithActor = z.infer<typeof ActivityEventWithActorSchema>;

/** Activity feed page response */
export type ActivityFeedPage = z.infer<typeof ActivityFeedPageSchema>;

/** Activity feed filter input */
export type ActivityFeedFilter = z.infer<typeof ActivityFeedFilterSchema>;

/** Activity event realtime payload */
export type ActivityEventRealtimePayload = z.infer<typeof ActivityEventRealtimePayloadSchema>;

// Typed payload types
export type TimerStartedPayload = z.infer<typeof TimerStartedPayloadSchema>;
export type TimerStoppedPayload = z.infer<typeof TimerStoppedPayloadSchema>;
export type EntryLoggedPayload = z.infer<typeof EntryLoggedPayloadSchema>;
export type EntryApprovalPayload = z.infer<typeof EntryApprovalPayloadSchema>;
export type GoalPayload = z.infer<typeof GoalPayloadSchema>;
export type MemberPayload = z.infer<typeof MemberPayloadSchema>;
export type ProjectCreatedPayload = z.infer<typeof ProjectCreatedPayloadSchema>;
export type ProjectMemberAddedPayload = z.infer<typeof ProjectMemberAddedPayloadSchema>;
